[package]
name = "server"
version = "0.1.0"
authors.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
s2n-quic = "1.49.0"
tokio = { version = "1", features = ["full"] }
compute = { path = "../compute" }
futures-util = "0.3.31"
tracing.workspace = true
tracing-subscriber = "0.3.18"
hex = "0.4.3"
bincode = "1.3.3"
anyhow = "1.0.91"
serde = "1.0"
bytes = "1.8.0"
